### ISSUE TITLE
Issue on targeting certain "untyped" mobs

### ISSUE THREAD

**Issue by Veyska** [parnic/LibDogTag-Unit-3.0#11]
Certain untyped mobs are throwing an error when targeted in 10.0.2 Retail.  I don't *think* their mob/whatever type changed with patch, but something obviously shifted under the hood even if only lurking in an API somewhere.  The "mobs" I've so far noticed this on are Wildseed of Regrowth in the Night Fae Queen's Conservatory and the Ashen Phylactery jars in the Sanctum of Domination raid; whether it's all Uncategorized or just some I'm not sure.  Error occurs every time you target them, but does not re-occur while continuing to target (so no error spam, it's a once-off per each time you target).  No performance issues noticed either, so as errors go it's both relatively uncommon and has no negative effects other than BugSack/BugCatcher yelping at me every once in a great while.

Tried re-installing IceHUD (v1.14.7), the addon I use that embeds this library, as well as installing LibDogTag-Unit-3.0 (v100002.1)separately, and neither made the error stop.

Error text as follows:
```
42x LibDogTag-3.0-20221115062710.20221115: Error with code "[Guild:Angle]" (Base;Unit). ...bs/LibDogTag-Unit-3.0/Categories/TooltipScanning.lua:71: attempt to index field '?' (a nil value)
[string "@IceHUD/libs/LibDogTag-3.0-20221115062710/LibDogTag-3.0.lua"]:304: in function <...eIceHUD/libs/LibDogTag-3.0/LibDogTag-3.0.lua:290>
[string "@IceHUD/libs/LibDogTag-3.0-20221115062710/LibDogTag-3.0.lua"]:333: in function 'UpdateFontString'
[string "@IceHUD/modules/TargetInfo.lua"]:1721: in function 'Update'
[string "@IceHUD/IceElement.lua"]:470: in function 'TargetChanged'
[string "@IceHUD/modules/TargetInfo.lua"]:1546: in function '?'
[string "@Ace3/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:114: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:114>
[string "=[C]"]: ?
[string "@Ace3/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:24: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:20>
[string "@Ace3/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:59: in function 'Fire'
[string "@Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: in function 'TurnOrActionStop'
[string "TURNORACTION"]:4: in function <[string "TURNORACTION"]:1>
```

**Comment by parnic** [comment]
Thanks for the details report - I'll check this out!

**Comment by parnic** [comment]
Fixed.
