### ISSUE TITLE
scanning tooltip accidentally empties the GameTooltip in classic era

### ISSUE THREAD

**Issue by frozn** [parnic/LibDogTag-Unit-3.0#14]
Hello,

it seems that the scanning tooltip in LibDogTag-Unit-3.0 accidentally empties the GameTooltip in classic era.

How to reproduce:

1. Install addon [IceHUD](https://www.curseforge.com/wow/addons/ice-hud).
2. Open IceHUD options with `/icehud` and make shure, that module "TargetInfo" is enabled (default) and "Line 3 Tag" is filled with `[Guild:Angle]` (default).
3. Mouse over a NPC. GameTooltip is fine:
![image](https://github.com/parnic/LibDogTag-Unit-3.0/assets/5655881/fe3c27e9-0f75-48e0-a238-ddfd89e448e0)
4. Click on the NPC hovering over. GameTooltip is empty because of scanning tooltip (\Categories\TooltipScanning.lua):
![image](https://github.com/parnic/LibDogTag-Unit-3.0/assets/5655881/1133089d-3b12-4b17-bea9-0aaa6438177d)

How to fix:

1. Change the line with `CreateFrame()` to set a unique frame name for the scanning tooltip:
https://github.com/parnic/LibDogTag-Unit-3.0/blob/7f9d5db1e5d2ea48525a8911ca059acea5e19445/Categories/TooltipScanning.lua#L21-L23
e.g. `tt = CreateFrame("GameTooltip", MAJOR_VERSION.."_"..MINOR_VERSION)`

After this change the GameTooltip won't accidentally be emptied by the scanning tooltip.

**Comment by parnic** [comment]
Thanks
