### ISSUE TITLE
NumAura (UnitAura) error in 11.0.2

### ISSUE THREAD

**Issue by Effeh** [parnic/LibDogTag-Unit-3.0#15]
Encountered this new 11.0.2 problem in TellMeWhen and was sent here

![image](https://github.com/user-attachments/assets/bef80ecd-9449-45be-8f78-f209e12f7f1a)

`5x LibDogTag-3.0-20240726033914.20240726: Error with code "[OUTLINE][NumAura(\"Unerring Proficiency\"):Hide(0)]" (Base;Stats;TMW;Unit). ...llMeWhen/Lib/LibDogTag-Unit-3.0/Categories/Auras.lua:35: attempt to call upvalue 'UnitAura' (a nil value)
[string "@TellMeWhen/Lib/LibDogTag-3.0-20240726033914/LibDogTag-3.0.lua"]:304: in function <...ddOns/TellMeWhen/Lib/LibDogTag-3.0/LibDogTag-3.0.lua:290>
[string "@TellMeWhen/Lib/LibDogTag-3.0-20240726033914/LibDogTag-3.0.lua"]:440: in function `AddFontString'
[string "@TellMeWhen/Components/IconModules/IconModule_Texts/Texts.lua"]:937: in function `OnKwargsUpdated'
[string "@TellMeWhen/Components/IconModules/IconModule_Texts/Texts.lua"]:891: in function `func'
[string "@TellMeWhen/TellMeWhen.lua"]:2802: in function `safecall'
[string "@TellMeWhen/Components/Core/IconModule.lua"]:94: in function `func'
[string "@TellMeWhen/TellMeWhen.lua"]:2802: in function `safecall'
[string "@TellMeWhen/Components/Core/BaseClasses/IconComponent.lua"]:213: in function `ImplementIntoIcon'
[string "@TellMeWhen/Components/Core/IconView.lua"]:280: in function `func'
[string "@TellMeWhen/TellMeWhen.lua"]:2802: in function `safecall'
[string "@TellMeWhen/Components/Core/BaseClasses/IconComponent.lua"]:213: in function `ImplementIntoIcon'
[string "@TellMeWhen/Components/Core/Icon.lua"]:1026: in function `func'
[string "@TellMeWhen/TellMeWhen.lua"]:2802: in function `safecall'
[string "@TellMeWhen/Components/Core/Group.lua"]:497: in function `func'
[string "@TellMeWhen/TellMeWhen.lua"]:2802: in function `safecall'
[string "@TellMeWhen/TellMeWhen.lua"]:2763: in function <TellMeWhen/TellMeWhen.lua:2720>`

**Comment by parnic** [comment]
Thanks, I'll take a look.

cc @ascott18
