### ISSUE TITLE
Client crash on Wrath Classic during Herald Volazj fight

### ISSUE THREAD

**Issue by parnic** [parnic/LibDogTag-Unit-3.0#8]
When it casts Insanity and creates enemy copies of the players, the game client crashes. The crash log points at line 41 in TooltipScanning.lua.

![image](https://user-images.githubusercontent.com/888126/192602157-54f8f4e5-33d0-428a-8372-8a81dc6688ec.png)

**Comment by parnic** [comment]
This is something Blizzard needs to fix since addons shouldn't be capable of crashing the game client.

@ascott18 the issue is `tt:ClearLines()` in Categories\TooltipScanning.lua. We've tried nil-checking `tt` but that didn't do it. If you've got any thoughts, I'm all ears. I'm inclined to bypass ClearLines in Wrath Classic only until Blizzard patches the crash or something, but I don't know what the actual problem at the game client level is.

**Comment by ascott18** [comment]
Yuck. Yeah, the only idea I have is to not call the function. Maybe only if in combat, and only for Wrath Classic?
